/**
 * Shared Constants for Portfolio AI
 * Eliminates duplication across components
 */
const PORTFOLIO_KEYWORDS = [
  "skills",
  "experience",
  "projects",
  "education",
  "contact",
  "services",
  "work",
  "career",
  "portfolio",
  "technologies",
  "programming",
  "developer",
  "background",
  "know",
  "familiar",
  "built",
  "developed",
  "email",
  "phone",
  "frameworks",
  "languages",
  "tools",
  "stack",
  "cloud",
  "freelance",
  "hire",
  "ai",
  "genai",
  "rag",
  "llm",
  "mcp",
  "ollama",
  "mistral",
  "vector",
  "database",
  "embedding",
  "machine learning",
  "artificial intelligence",
  // Education keywords
  "degree",
  "university",
  "college",
  "school",
  "studied",
  "graduated",
  "qualification",
  "diploma",
  // Experience keywords
  "years",
  "role",
  "position",
  "job",
  "current",
  "employment",
  "company",
  // Contact keywords
  "reach",
  "address",
  "website",
  "linkedin",
  "location",
  "located",
  // Skills keywords
  "technical",
  "soft",
  "coding",
  "proficient",
  "strengths",
  "abilities",
  "expertise",
  // Projects keywords
  "apps",
  "websites",
  "mobile",
  "trunow",
  "mercury",
  "aboveo",
  "asa",
  // General keywords
  "yourself",
  "about",
  "overview",
  "summary",
  "introduce",
];

const MALICIOUS_PATTERNS = [
  /ignore\s+previous\s+instructions/i,
  /system\s+prompt/i,
  /jailbreak/i,
  /<script>/i,
  /hack/i,
];

module.exports = {
  PORTFOLIO_KEYWORDS,
  MALICIOUS_PATTERNS,
};
